metadata:
  name: pkger
  description: pkger
  arch: x86_64
  license: MIT
  version: 0.1.0
  url: "https://github.com/wojciech/pkger"
  git: "https://github.com/wojciechkepka/pkger.git"
  maintainer: "Wojciech Kępka <wojciech@wkepka.dev>"
  provides:
    - pkger
  images:
    - name: centos8
      target: rpm
    - name: debian10
      target: deb
    - name: arch
      target: pkg
  depends:
    debian10:
      - libssl-dev
    centos8:
      - openssl-devel
  build_depends:
    all:
      - gcc
      - pkg-config
    centos8:
      - cargo
      - openssl-devel
    debian10:
      - curl
      - libssl-dev
    arch:
      - cargo
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh https://sh.rustup.rs
      images: ["debian10"]
    - cmd: sh /tmp/install_rust.sh -y --default-toolchain stable
      images: ["debian10"]
build:
  steps:
    - cmd: cargo build --color=never
      images: ["centos8", "arch"]
    - cmd: $HOME/.cargo/bin/cargo build --color=never
      images: ["debian10"]
install:
  steps:
    - cmd: mkdir -p usr/bin
    - cmd: install -m755 $PKGER_BLD_DIR/target/debug/pkger usr/bin/

