---
metadata:
  name: test-package
  version: 0.1.0
  description: pkger test package
  arch: x86_64
  license: MIT
  images: [ centos8, debian10 ]
configure:
  steps:
    - cmd: mkdir -p $PKGER_OUT_DIR/$RECIPE_VERSION/$RECIPE
build:
  working_dir: ${PKGER_OUT_DIR}/${RECIPE_VERSION}/${RECIPE}
  steps:
    - cmd: echo $PWD
install:
  steps:
    - cmd: mkdir -p $PKGER_OUT_DIR/test/deb
      images: ["debian10"]
    - cmd: mkdir -p $PKGER_OUT_DIR/test/rpm
      images: ["centos8"]
    - cmd: echo "123" > $PKGER_OUT_DIR/test/rpm/test_file
      images: ["centos8"]
    - cmd: echo "321" > $PKGER_OUT_DIR/test/deb/test_file
      images: ["debian10"]
