---
from: base-package
metadata:
  name: child-package2
  version: 0.3.0
  description: pkger child package2 testing recipe inheritance from base-package
build:
  steps:
    - cmd: echo 123
install:
  shell: /bin/bash
  steps:
    - cmd: >-
        if [ ! -f ${RECIPE}_${RECIPE_VERSION} ]; then exit 0; else
        echo "Test file ${RECIPE}_${RECIPE_VERSION} should not exist on child-package2"; exit 1; fi
